Feature/hana
GA-Team2/burang-narang pull request #100
Opened 2022-10-27 09:49 UTC by karedonkatsu

## 제목

make 후 detail 페이지 이동 매핑

## 작업 내용

make 후 detail 페이지 이동 매핑

## 리뷰어들이 신경써야 할 만한 사항

신경써야 할 만한 사항

2022-10-27 13:25 UTC, FineScore requested changes
수정 부탁드립니다

2022-10-27 13:25 UTC, FineScore commented on src/main/resources/application.properties
> +#\uC9D1\uC5D0\uC11C\uB294 \uC9C0\uC6B0\uACE0
이게 뭐죠??? ㅋㅋㅋㅋㅋㅋㅋㅋ

2022-10-28 05:04 UTC, karedonkatsu commented on src/main/resources/application.properties
> +#\uC9D1\uC5D0\uC11C\uB294 \uC9C0\uC6B0\uACE0
수정했습니다

2022-10-28 05:17 UTC, Next-Episode approved these changes

2022-10-28 05:17 UTC, FineScore approved these changes
승인

2022-10-28 05:17 UTC, merged