Feature/hanb
GA-Team2/burang-narang pull request #27
Opened 2022-10-05 02:37 UTC by Next-Episode

## 제목

index, signUP, Login Remark

## 작업 내용

메인, 로그인, 회원가입 페이지 주석

## 리뷰어들이 신경써야 할 만한 사항

Servlet 설정 궁금하시면 따로 설명해드립니다. 주석으로 설명하기가 애매하네요.

2022-10-05 05:20 UTC, FineScore requested changes
클래스와 메서드 위에는 javadoc 형식의 주석을 달아주세요
코드 컨벤션의 4.3 주석 작성 예시를 참조해주세요

2022-10-05 08:01 UTC, karedonkatsu approved these changes

2022-10-05 08:05 UTC, FineScore submitted a review, later dismissed
승인 테스트

2022-10-06 00:30 UTC, FineScore requested changes
수정 한번 부탁드립니다

2022-10-06 00:30 UTC, FineScore commented on src/main/webapp/scripts/script_index.js
> +window.onload = function () {
포맷팅 해주세요

2022-10-06 00:30 UTC, FineScore commented on src/main/webapp/index.jsp
> +          <% /*비 로그인 시 구성 */ if(nick == null){ %>
주석을 별도로 써주세요

2022-10-06 00:30 UTC, FineScore commented on src/main/webapp/index.jsp
>  	</script> -->
나중에 사용할 코드인가요?
아니라면 삭제 부탁드립니다

2022-10-06 00:30 UTC, FineScore commented on src/main/webapp/index.jsp
> +System.out.println("nickname : " + nick); /* D-day를 표시하기위한 DAO,DTO 선언
제가 쓴 주석은 지워주세요
죄송합니다 ㅠ
그 후에 주석 한번 정리해주세요

2022-10-06 00:54 UTC, FineScore approved these changes
나중에 JS도 주석 달아주세요
승인

2022-10-06 00:56 UTC, hjwkd approved these changes

2022-10-06 00:56 UTC, merged