Feature/hanb
GA-Team2/burang-narang pull request #70
Opened 2022-10-18 09:46 UTC by Next-Episode

## 제목

혼잡도 스프링 이식 작업

## 작업 내용

ajax를 스프링이 지원하는 형식으로 이식하여 혼잡도를 구현

## 리뷰어들이 신경써야 할 만한 사항

놉

2022-10-18 09:49 UTC, FineScore requested changes
수정해주세요

2022-10-18 09:49 UTC, FineScore commented on src/main/java/org/ga2/buna/controller/plandatecheck/PlanDateCheckRestController.java
> +    @RequestMapping(value = "/DB", produces = MediaType.APPLICATION_JSON_VALUE)
url은 소문자로 쓰는 것이 좋습니다

2022-10-18 09:49 UTC, karedonkatsu submitted a review, later dismissed
승인

2022-10-18 09:50 UTC, FineScore commented on src/main/java/org/ga2/buna/controller/plandatecheck/PlanDateCheckRestController.java
> +    @RequestMapping(value = "/DB", produces = MediaType.APPLICATION_JSON_VALUE)
url도 의미를 넣어서 지정해주세요

2022-10-19 05:45 UTC, FineScore approved these changes
승인

2022-10-19 05:48 UTC, karedonkatsu approved these changes
승인

2022-10-19 05:48 UTC, merged